// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    daily_refund_trend: {
        name: "daily_refund_trend";
        parameters: {
          /** STRING - use sql.string() */
          catalog: SQLStringMarker;
          /** STRING - use sql.string() */
          schema: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType DATE */
          return_date: string;
          /** @sqlType DOUBLE */
          total_refund_usd: number;
        }>;
      };
    returns_by_product: {
        name: "returns_by_product";
        parameters: {
          /** STRING - use sql.string() */
          catalog: SQLStringMarker;
          /** STRING - use sql.string() */
          schema: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          product_name: string;
          /** @sqlType BIGINT */
          return_count: number;
          /** @sqlType DOUBLE */
          total_refund_usd: number;
        }>;
      };
    worst_lots: {
        name: "worst_lots";
        parameters: {
          /** STRING - use sql.string() */
          catalog: SQLStringMarker;
          /** STRING - use sql.string() */
          schema: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          lot_id: string;
          /** @sqlType STRING */
          product_name: string;
          /** @sqlType STRING */
          facility: string;
          /** @sqlType STRING */
          region: string;
          /** @sqlType BIGINT */
          return_count: number;
          /** @sqlType BIGINT */
          units_sold: number;
          /** @sqlType DOUBLE */
          return_rate_pct: number;
          /** @sqlType DOUBLE */
          total_refund_usd: number;
        }>;
      };
  }
}
